apiVersion: v1
kind: Service
metadata:
  name: art-service
  labels:
    app: art-uclabs
spec:
  selector:
    app: art-uclabs
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31333
