apiVersion: apps/v1 
kind: Deployment
metadata:
  name: art-deployment
spec:
  selector:
    matchLabels:
      app: art-uclabs
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: art-uclabs
    spec:
      containers:
      - name: art-uclabs
        image: arthur1cp/devops-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
